spring.application.name=interview-simulator
spring.datasource.url=jdbc:mysql://localhost:3306/interview_simulator
spring.datasource.username=root
spring.datasource.password=3139@Anisha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
